require "../utils/errors"

module Doma
  # Owns the "wire doma's shell wrapper into the user's rc file" flow,
  # decoupled from the CLI command so the logic is testable without
  # spawning a subprocess. The actual rc edit is dead simple — append a
  # single `eval "$(doma init <shell>)"` line — the value here is in the
  # detection (which shell, which rc file) and idempotency (don't append
  # twice if the user runs `doma install` again).
  module Installer
    extend self

    # Sentinel comment placed alongside the eval line. We grep for this
    # to detect prior installations rather than the eval line itself,
    # because the user may have customized the eval (different binary
    # path, different shell name) and we still want to recognize "doma
    # already touched this file."
    MARKER     = "# >>> doma shell integration >>>"
    END_MARKER = "# <<< doma shell integration <<<"

    record Plan,
      shell : String,
      rc_path : String,
      block : String,
      already_installed : Bool

    def detect_shell : String?
      raw = ENV["SHELL"]?
      return unless raw
      base = File.basename(raw)
      case base
      when "bash", "zsh", "fish" then base
      end
    end

    # Resolves the rc file for a given shell, honoring the conventions
    # most users actually have. We don't try to be clever about
    # `~/.bash_profile` vs `~/.bashrc` etc. — `bash` users on macOS in
    # particular tend to have either, so we go with the most common
    # interactive-shell file.
    def rc_path_for(shell : String) : String
      case shell
      when "zsh"  then File.expand_path("~/.zshrc", home: true)
      when "bash" then File.expand_path("~/.bashrc", home: true)
      when "fish" then File.expand_path("~/.config/fish/config.fish", home: true)
      else
        raise ValidationError.new("unsupported shell '#{shell}' (try bash, zsh, or fish)")
      end
    end

    # The block we paste into the rc file. Wrapping `eval` between the
    # markers means a future uninstall could `sed` between them; today
    # the markers' main job is idempotency detection.
    def block_for(shell : String) : String
      eval_line = case shell
                  when "fish" then "doma setup init fish | source"
                  else             %(eval "$(doma setup init #{shell})")
                  end
      <<-RC
        #{MARKER}
        # Generated by `doma setup install` — wraps `doma cd` so it changes
        # the shell's working directory. Safe to delete (along with the
        # closing marker below) if you no longer use doma.
        #{eval_line}
        #{END_MARKER}
        RC
    end

    def plan(shell : String) : Plan
      rc = rc_path_for(shell)
      block = block_for(shell)
      installed = File.exists?(rc) && File.read(rc).includes?(MARKER)
      Plan.new(shell: shell, rc_path: rc, block: block, already_installed: installed)
    end

    # Performs the rc-file append. Caller is expected to have prompted
    # the user already (or to have skipped via `--yes`). No-op when the
    # marker is already present.
    def install!(plan : Plan) : Symbol
      return :already_installed if plan.already_installed
      Dir.mkdir_p(File.dirname(plan.rc_path))
      # Preserve a blank line before the block when the file isn't
      # already empty / newline-terminated, so the block doesn't fuse
      # to whatever was written previously.
      preamble = needs_separator?(plan.rc_path) ? "\n" : ""
      File.open(plan.rc_path, "a") do |f|
        f.print preamble
        f.puts plan.block
      end
      :installed
    end

    private def needs_separator?(path : String) : Bool
      return false unless File.file?(path)
      size = File.size(path)
      return false if size == 0
      File.open(path, "r") do |f|
        f.seek(size - 1)
        f.read_byte != 0x0a # '\n'
      end
    end
  end
end
