require "../utils/errors"
require "../utils/validator"

module Doma
  # Owns the "wire doma's shell wrapper into the user's rc file" flow,
  # decoupled from the CLI command so the logic is testable without
  # spawning a subprocess. The actual rc edit is dead simple — append a
  # single `eval "$(doma init <shell>)"` line — the value here is in the
  # detection (which shell, which rc file) and idempotency (don't append
  # twice if the user runs `doma install` again).
  module Installer
    extend self

    # Sentinel comment placed alongside the eval line. We grep for this
    # to detect prior installations rather than the eval line itself,
    # because the user may have customized the eval (different binary
    # path, different shell name) and we still want to recognize "doma
    # already touched this file."
    MARKER     = "# >>> doma shell integration >>>"
    END_MARKER = "# <<< doma shell integration <<<"

    record Plan,
      shell : String,
      rc_path : String,
      block : String,
      already_installed : Bool

    def detect_shell : String?
      raw = ENV["SHELL"]?
      return unless raw
      base = File.basename(raw)
      case base
      when "bash", "zsh", "fish" then base
      end
    end

    # Resolves the rc file for a given shell, honoring the conventions
    # most users actually have. We don't try to be clever about
    # `~/.bash_profile` vs `~/.bashrc` etc. — `bash` users on macOS in
    # particular tend to have either, so we go with the most common
    # interactive-shell file.
    def rc_path_for(shell : String) : String
      case shell
      when "zsh"  then Validator.expand_home("~/.zshrc")
      when "bash" then Validator.expand_home("~/.bashrc")
      when "fish" then Validator.expand_home("~/.config/fish/config.fish")
      else
        raise ValidationError.new("unsupported shell '#{shell}' (try bash, zsh, or fish)")
      end
    end

    # The block we paste into the rc file. Wrapping `eval` between the
    # markers means a future uninstall could `sed` between them; today
    # the markers' main job is idempotency detection.
    def block_for(shell : String) : String
      eval_line = case shell
                  when "fish" then "doma setup init fish | source"
                  else             %(eval "$(doma setup init #{shell})")
                  end
      <<-RC
        #{MARKER}
        # Generated by `doma setup install` — wraps `doma cd` so it changes
        # the shell's working directory. Safe to delete (along with the
        # closing marker below) if you no longer use doma.
        #{eval_line}
        #{END_MARKER}
        RC
    end

    # Substring that uniquely identifies our installed line across all
    # supported shells — bash/zsh eval into it, fish pipes into `source`.
    # Used as a fallback to detect prior installs when the markers have
    # been hand-removed but the working line is still there.
    INSTALL_SIGNATURE = "doma setup init"

    def plan(shell : String) : Plan
      rc = rc_path_for(shell)
      block = block_for(shell)
      installed = installed?(rc)
      Plan.new(shell: shell, rc_path: rc, block: block, already_installed: installed)
    end

    # Detect a prior install by either the bookend marker or the bare
    # `doma setup init` line. Checking just the marker meant a user who
    # stripped the markers but kept the eval would get a duplicate block
    # appended on the next `doma setup install`. For the eval-line
    # fallback we skip commented lines (`# TODO: doma setup init`) so
    # recovery notes or pasted instructions don't false-positive — the
    # MARKER itself IS a comment though, so we test it before the
    # comment skip.
    private def installed?(rc : String) : Bool
      return false unless File.exists?(rc)
      File.each_line(rc) do |line|
        stripped = line.lstrip
        return true if stripped.includes?(MARKER)
        next if stripped.empty? || stripped.starts_with?('#')
        return true if stripped.includes?(INSTALL_SIGNATURE)
      end
      false
    rescue IO::Error
      # Unreadable rc file: treat as not-installed; the append in
      # `install!` will surface its own (clean) error if the file is
      # genuinely inaccessible.
      false
    end

    # Performs the rc-file append. Caller is expected to have prompted
    # the user already (or to have skipped via `--yes`). No-op when the
    # marker is already present.
    def install!(plan : Plan) : Symbol
      return :already_installed if plan.already_installed
      Dir.mkdir_p(File.dirname(plan.rc_path))
      # Preserve a blank line before the block when the file isn't
      # already empty / newline-terminated, so the block doesn't fuse
      # to whatever was written previously.
      preamble = needs_separator?(plan.rc_path) ? "\n" : ""
      File.open(plan.rc_path, "a") do |f|
        f.print preamble
        f.puts plan.block
      end
      :installed
    rescue ex : IO::Error
      raise Doma::Error.new(
        "cannot write shell integration to #{plan.rc_path}: #{ex.message}"
      )
    end

    private def needs_separator?(path : String) : Bool
      return false unless File.file?(path)
      size = File.size(path)
      return false if size == 0
      File.open(path, "r") do |f|
        f.seek(size - 1)
        f.read_byte != 0x0a # '\n'
      end
    end
  end
end
