require "option_parser"
require "../../utils/errors"

module Doma::CLI
  # Emits a shell wrapper so `doma cd` actually changes the parent
  # shell's working directory. A child process can't `cd` its parent,
  # so this is the standard pattern: ship a thin function that captures
  # the output and runs `cd` itself.
  #
  # Users typically install this with:
  #
  #   eval "$(doma setup init zsh)"      # or bash / fish
  class InitCommand
    SUPPORTED = %w[bash zsh fish]

    def run(args : Array(String))
      shell : String? = nil

      parser = OptionParser.new do |p|
        p.banner = "Usage: doma setup init <bash|zsh|fish>"
        p.on("-h", "--help", "Show help") do
          puts p
          exit 0
        end
        p.unknown_args do |before, after|
          shell ||= before.first? || after.first?
        end
      end
      parser.parse(args)

      target = shell
      raise Doma::ValidationError.new("shell is required (one of: #{SUPPORTED.join(", ")})") unless target

      case target
      when "bash", "zsh"
        STDOUT.puts posix_wrapper
      when "fish"
        STDOUT.puts fish_wrapper
      else
        raise Doma::ValidationError.new(
          "unsupported shell '#{target}' (supported: #{SUPPORTED.join(", ")})"
        )
      end
    end

    # Bash and zsh share enough syntax that one wrapper covers both. The
    # function shadows the binary in PATH for the wrapped subcommands and
    # delegates everything else through `command doma` so behavior is
    # otherwise identical.
    private def posix_wrapper : String
      <<-SH
        # doma shell integration (bash/zsh)
        #
        # Generated by `doma setup init`. Add to your rc file:
        #   eval "$(doma setup init bash)"   # or zsh
        #
        # Wraps `doma cd` so it actually changes directory instead of just
        # printing the resolved path.

        doma() {
          if [ "$1" = "cd" ]; then
            local __doma_target
            __doma_target="$(command doma "$@")" || return $?
            [ -n "$__doma_target" ] && builtin cd -- "$__doma_target"
          else
            command doma "$@"
          fi
        }
        SH
    end

    private def fish_wrapper : String
      <<-FISH
        # doma shell integration (fish)
        #
        # Generated by `doma setup init fish`. Add to ~/.config/fish/config.fish:
        #   doma setup init fish | source

        function doma
          if test (count $argv) -gt 0; and test $argv[1] = "cd"
            set -l __doma_target (command doma $argv)
            or return $status
            if test -n "$__doma_target"
              builtin cd -- $__doma_target
            end
          else
            command doma $argv
          end
        end
        FISH
    end
  end
end
