require "option_parser"
require "../../utils/errors"

module Doma::CLI
  # Emits a shell wrapper so `doma cd` actually changes the parent
  # shell's working directory. A child process can't `cd` its parent,
  # so this is the standard pattern: ship a thin function that captures
  # the output and runs `cd` itself.
  #
  # Users typically install this with:
  #
  #   eval "$(doma setup init zsh)"      # or bash / fish
  class InitCommand
    SUPPORTED = %w[bash zsh fish]

    def run(args : Array(String))
      shell : String? = nil

      parser = OptionParser.new do |p|
        p.banner = "Usage: doma setup init <bash|zsh|fish>"
        p.on("-h", "--help", "Show help") do
          puts p
          exit 0
        end
        p.unknown_args do |before, after|
          shell ||= before.first? || after.first?
        end
      end
      parser.parse(args)

      target = shell
      raise Doma::ValidationError.new("shell is required (one of: #{SUPPORTED.join(", ")})") unless target

      case target
      when "bash", "zsh"
        STDOUT.puts posix_wrapper
      when "fish"
        STDOUT.puts fish_wrapper
      else
        raise Doma::ValidationError.new(
          "unsupported shell '#{target}' (supported: #{SUPPORTED.join(", ")})"
        )
      end
    end

    # Bash and zsh share enough syntax that one wrapper covers both. The
    # function shadows the binary in PATH so directory-changing commands work
    # as expected — the binary can't change its parent shell's cwd, so the
    # function captures the picked path and runs `cd` itself:
    #   - `doma cd <tag>` → `doma list -t <tag> --pick`
    #   - bare `doma` / `doma tui` → the interactive finder; the path it
    #     prints on selection becomes the new cwd
    # Everything else passes through to `command doma` unchanged.
    private def posix_wrapper : String
      <<-SH
        # doma shell integration (bash/zsh)
        #
        # Generated by `doma setup init`. Add to your rc file:
        #   eval "$(doma setup init bash)"   # or zsh
        #
        # Lets directory-picking commands change the shell's cwd (a child
        # process can't do that itself). `doma cd <tag>` resolves via
        # `doma list --pick`; bare `doma` and `doma tui` open the interactive
        # finder and `cd` to whatever you select.

        doma() {
          if [ "$1" = "cd" ]; then
            shift
            local __doma_target
            if [ $# -eq 0 ]; then
              __doma_target="$(command doma list --pick)" || return $?
            else
              __doma_target="$(command doma list -t "$1" --pick)" || return $?
            fi
            [ -n "$__doma_target" ] && builtin cd -- "$__doma_target"
          elif [ $# -eq 0 ] || [ "$1" = "tui" ]; then
            local __doma_target
            __doma_target="$(command doma "$@")" || return $?
            [ -n "$__doma_target" ] && builtin cd -- "$__doma_target"
          else
            command doma "$@"
          fi
        }
        SH
    end

    private def fish_wrapper : String
      <<-FISH
        # doma shell integration (fish)
        #
        # Generated by `doma setup init fish`. Add to ~/.config/fish/config.fish:
        #   doma setup init fish | source
        #
        # Lets directory-picking commands change the shell's cwd. `doma cd
        # <tag>` resolves via `doma list --pick`; bare `doma` and `doma tui`
        # open the interactive finder and `cd` to whatever you select.

        function doma
          if test (count $argv) -gt 0; and test $argv[1] = "cd"
            set -l __doma_args $argv[2..-1]
            set -l __doma_target
            if test (count $__doma_args) -eq 0
              set __doma_target (command doma list --pick)
            else
              set __doma_target (command doma list -t $__doma_args[1] --pick)
            end
            or return $status
            if test -n "$__doma_target"
              builtin cd -- $__doma_target
            end
          else if test (count $argv) -eq 0; or test $argv[1] = "tui"
            set -l __doma_target (command doma $argv)
            or return $status
            if test -n "$__doma_target"
              builtin cd -- $__doma_target
            end
          else
            command doma $argv
          end
        end
        FISH
    end
  end
end
